/* generated by Svelte v3.32.3 */
import { SvelteComponent, init, safe_not_equal } from '../web_modules/svelte/internal/index.mjs';

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Component;