/* generated by Svelte v3.32.3 */
import { SvelteComponent, init, safe_not_equal } from '/spa/web_modules/svelte/internal/index.mjs';

const makeTitle = filename => {
	if (filename == "index.json") {
		return "Home";
	} else if (filename) {
		// Remove file extension.
		filename = filename.split(".").slice(0, -1).join(".");

		// Convert underscores and hyphens to spaces.
		filename = filename.replace(/_|-/g, " ");

		// Capitalize first letter of each word.
		filename = filename.split(" ").map(s => s.charAt(0).toUpperCase() + s.substring(1)).join(" ");
	}

	return filename;
};

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Component;
export { makeTitle };