/* generated by Svelte v3.23.2 */
import { SvelteComponent, init, safe_not_equal } from '/spa/web_modules/svelte/internal/index.js';

const sortByDate = (items, order) => {
	items.sort((a, b) => {
		// Must have a field specifically named "date" to work.
		// Feel free to extend to other custom named date fields.
		if (a.fields.hasOwnProperty("date") && b.fields.hasOwnProperty("date")) {
			let aDate = new Date(a.fields.date);
			let bDate = new Date(b.fields.date);

			if (order == "oldest") {
				return aDate - bDate;
			}

			return bDate - aDate;
		}
	});

	return items;
};

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Component;
export { sortByDate };