import{cubicInOut,linear,cubicOut}from"../easing/index.mjs";import{is_function,assign}from"../internal/index.mjs";function __rest(e,t){o={};for(n in e)Object.prototype.hasOwnProperty.call(e,n)&&t.indexOf(n)<0&&(o[n]=e[n]);if(e!=null&&typeof Object.getOwnPropertySymbols=="function")for(var o,s=0,n=Object.getOwnPropertySymbols(e);s<n.length;s++)t.indexOf(n[s])<0&&Object.prototype.propertyIsEnumerable.call(e,n[s])&&(o[n[s]]=e[n[s]]);return o}function blur(e,{delay:t=0,duration:n=400,easing:s=cubicInOut,amount:o=5,opacity:i=0}={}){const a=getComputedStyle(e),r=+a.opacity,c=a.filter==="none"?"":a.filter,l=r*(1-i);return{delay:t,duration:n,easing:s,css:(e,t)=>`opacity: ${r-l*t}; filter: ${c} blur(${t*o}px);`}}function fade(e,{delay:t=0,duration:n=400,easing:s=linear}={}){const o=+getComputedStyle(e).opacity;return{delay:t,duration:n,easing:s,css:e=>`opacity: ${e*o}`}}function fly(e,{delay:t=0,duration:n=400,easing:s=cubicOut,x:o=0,y:i=0,opacity:a=0}={}){const r=getComputedStyle(e),c=+r.opacity,l=r.transform==="none"?"":r.transform,d=c*(1-a);return{delay:t,duration:n,easing:s,css:(e,t)=>`
			transform: ${l} translate(${(1-e)*o}px, ${(1-e)*i}px);
			opacity: ${c-d*t}`}}function slide(e,{delay:t=0,duration:n=400,easing:s=cubicOut}={}){const o=getComputedStyle(e),i=+o.opacity,a=parseFloat(o.height),r=parseFloat(o.paddingTop),c=parseFloat(o.paddingBottom),l=parseFloat(o.marginTop),d=parseFloat(o.marginBottom),u=parseFloat(o.borderTopWidth),h=parseFloat(o.borderBottomWidth);return{delay:t,duration:n,easing:s,css:e=>"overflow: hidden;"+`opacity: ${Math.min(e*20,1)*i};`+`height: ${e*a}px;`+`padding-top: ${e*r}px;`+`padding-bottom: ${e*c}px;`+`margin-top: ${e*l}px;`+`margin-bottom: ${e*d}px;`+`border-top-width: ${e*u}px;`+`border-bottom-width: ${e*h}px;`}}function scale(e,{delay:t=0,duration:n=400,easing:s=cubicOut,start:o=0,opacity:i=0}={}){const a=getComputedStyle(e),r=+a.opacity,c=a.transform==="none"?"":a.transform,l=1-o,d=r*(1-i);return{delay:t,duration:n,easing:s,css:(e,t)=>`
			transform: ${c} scale(${1-l*t});
			opacity: ${r-d*t}
		`}}function draw(e,{delay:t=0,speed:n,duration:s,easing:o=cubicInOut}={}){const i=e.getTotalLength();return s===void 0?n===void 0?s=800:s=i/n:typeof s=="function"&&(s=s(i)),{delay:t,duration:s,easing:o,css:(e,t)=>`stroke-dasharray: ${e*i} ${t*i}`}}function crossfade(e){var{fallback:t}=e,i=__rest(e,["fallback"]);const n=new Map,s=new Map;function a(e,t,n){const{delay:l=0,duration:o=e=>Math.sqrt(e)*30,easing:d=cubicOut}=assign(assign({},i),n),s=t.getBoundingClientRect(),a=e.left-s.left,r=e.top-s.top,u=e.width/s.width,h=e.height/s.height,m=Math.sqrt(a*a+r*r),c=getComputedStyle(t),f=c.transform==="none"?"":c.transform,p=+c.opacity;return{delay:l,duration:is_function(o)?o(m):o,easing:d,css:(e,t)=>`
				opacity: ${e*p};
				transform-origin: top left;
				transform: ${f} translate(${t*a}px,${t*r}px) scale(${e+(1-e)*u}, ${e+(1-e)*h});
			`}}function o(e,n,s){return(o,i)=>(e.set(i.key,{rect:o.getBoundingClientRect()}),()=>{if(n.has(i.key)){const{rect:e}=n.get(i.key);return n.delete(i.key),a(e,o,i)}return e.delete(i.key),t&&t(o,i,s)})}return[o(s,n,!1),o(n,s,!0)]}export{blur,crossfade,draw,fade,fly,scale,slide}