/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	add_flush_callback,
	add_render_callback,
	append,
	attr,
	bind,
	binding_callbacks,
	check_outros,
	children,
	claim_component,
	claim_element,
	claim_space,
	claim_text,
	create_animation,
	create_bidirectional_transition,
	create_component,
	destroy_component,
	destroy_each,
	detach,
	element,
	empty,
	fix_and_outro_and_destroy_block,
	fix_position,
	group_outros,
	init,
	insert,
	is_function,
	listen,
	mount_component,
	noop,
	null_to_empty,
	prevent_default,
	run_all,
	safe_not_equal,
	set_data,
	set_input_value,
	space,
	svg_element,
	text,
	transition_in,
	transition_out,
	update_keyed_each
} from '../../web_modules/svelte/internal/index.mjs';

import { isDate, makeDate, formatDate } from './dates.js';

// Accordion
import { slide } from '../../web_modules/svelte/transition/index.mjs';

// Drag and drop
import { flip } from '../../web_modules/svelte/animate/index.mjs';

function get_each_context_1(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[41] = list[i][0];
	child_ctx[39] = list[i][1];
	child_ctx[42] = list;
	child_ctx[43] = i;
	return child_ctx;
}

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[39] = list[i];
	child_ctx[40] = list;
	child_ctx[41] = i;
	return child_ctx;
}

// (184:49) 
function create_if_block_11(ctx) {
	let fieldset;
	let current;
	let each_value_1 = Object.entries(/*field*/ ctx[0]);
	let each_blocks = [];

	for (let i = 0; i < each_value_1.length; i += 1) {
		each_blocks[i] = create_each_block_1(get_each_context_1(ctx, each_value_1, i));
	}

	const out = i => transition_out(each_blocks[i], 1, 1, () => {
		each_blocks[i] = null;
	});

	return {
		c() {
			fieldset = element("fieldset");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
		},
		l(nodes) {
			fieldset = claim_element(nodes, "FIELDSET", {});
			var fieldset_nodes = children(fieldset);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(fieldset_nodes);
			}

			fieldset_nodes.forEach(detach);
		},
		m(target, anchor) {
			insert(target, fieldset, anchor);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(fieldset, null);
			}

			current = true;
		},
		p(ctx, dirty) {
			if (dirty[0] & /*field*/ 1) {
				each_value_1 = Object.entries(/*field*/ ctx[0]);
				let i;

				for (i = 0; i < each_value_1.length; i += 1) {
					const child_ctx = get_each_context_1(ctx, each_value_1, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
						transition_in(each_blocks[i], 1);
					} else {
						each_blocks[i] = create_each_block_1(child_ctx);
						each_blocks[i].c();
						transition_in(each_blocks[i], 1);
						each_blocks[i].m(fieldset, null);
					}
				}

				group_outros();

				for (i = each_value_1.length; i < each_blocks.length; i += 1) {
					out(i);
				}

				check_outros();
			}
		},
		i(local) {
			if (current) return;

			for (let i = 0; i < each_value_1.length; i += 1) {
				transition_in(each_blocks[i]);
			}

			current = true;
		},
		o(local) {
			each_blocks = each_blocks.filter(Boolean);

			for (let i = 0; i < each_blocks.length; i += 1) {
				transition_out(each_blocks[i]);
			}

			current = false;
		},
		d(detaching) {
			if (detaching) detach(fieldset);
			destroy_each(each_blocks, detaching);
		}
	};
}

// (101:47) 
function create_if_block_6(ctx) {
	let main;
	let div0;
	let p;
	let div0_class_value;
	let div0_style_value;
	let t;
	let div1;
	let each_blocks = [];
	let each_1_lookup = new Map();
	let current;
	let mounted;
	let dispose;
	let each_value = /*field*/ ctx[0];

	const get_key = ctx => /*compID*/ ctx[12] = /*isOpen*/ ctx[3]
	? /*key*/ ctx[41]
	: /*value*/ ctx[39].constructor === ({}).constructor
		? /*value*/ ctx[39][Object.keys(/*value*/ ctx[39])[0]]
		: /*value*/ ctx[39];

	for (let i = 0; i < each_value.length; i += 1) {
		let child_ctx = get_each_context(ctx, each_value, i);
		let key = get_key(child_ctx);
		each_1_lookup.set(key, each_blocks[i] = create_each_block(key, child_ctx));
	}

	return {
		c() {
			main = element("main");
			div0 = element("div");
			p = element("p");
			t = space();
			div1 = element("div");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			this.h();
		},
		l(nodes) {
			main = claim_element(nodes, "MAIN", { class: true });
			var main_nodes = children(main);
			div0 = claim_element(main_nodes, "DIV", { id: true, class: true, style: true });
			var div0_nodes = children(div0);
			p = claim_element(div0_nodes, "P", { class: true });
			children(p).forEach(detach);
			div0_nodes.forEach(detach);
			t = claim_space(main_nodes);
			div1 = claim_element(main_nodes, "DIV", { class: true });
			var div1_nodes = children(div1);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(div1_nodes);
			}

			div1_nodes.forEach(detach);
			main_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(p, "class", "svelte-1dgf7zq");
			attr(div0, "id", "ghost");
			attr(div0, "class", div0_class_value = "" + (null_to_empty(/*grabbed*/ ctx[6] ? "item haunting" : "item") + " svelte-1dgf7zq"));
			attr(div0, "style", div0_style_value = "top: " + (/*mouseY*/ ctx[7] + /*offsetY*/ ctx[8] - /*layerY*/ ctx[9]) + "px");
			attr(div1, "class", "list svelte-1dgf7zq");
			attr(main, "class", "dragdroplist svelte-1dgf7zq");
		},
		m(target, anchor) {
			insert(target, main, anchor);
			append(main, div0);
			append(div0, p);
			/*div0_binding*/ ctx[24](div0);
			append(main, t);
			append(main, div1);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(div1, null);
			}

			current = true;

			if (!mounted) {
				dispose = [
					listen(div1, "mousemove", /*mousemove_handler*/ ctx[33]),
					listen(div1, "touchmove", /*touchmove_handler_1*/ ctx[34]),
					listen(div1, "mouseup", /*mouseup_handler*/ ctx[35]),
					listen(div1, "touchend", /*touchend_handler*/ ctx[36])
				];

				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (!current || dirty[0] & /*grabbed*/ 64 && div0_class_value !== (div0_class_value = "" + (null_to_empty(/*grabbed*/ ctx[6] ? "item haunting" : "item") + " svelte-1dgf7zq"))) {
				attr(div0, "class", div0_class_value);
			}

			if (!current || dirty[0] & /*mouseY, offsetY, layerY*/ 896 && div0_style_value !== (div0_style_value = "top: " + (/*mouseY*/ ctx[7] + /*offsetY*/ ctx[8] - /*layerY*/ ctx[9]) + "px")) {
				attr(div0, "style", div0_style_value);
			}

			if (dirty[0] & /*grabbed, compID, field, label, openKeys, removeItem, removesItems, accordion, moveItem, grab, dragEnter, touchEnter, isOpen*/ 768095) {
				each_value = /*field*/ ctx[0];
				group_outros();
				for (let i = 0; i < each_blocks.length; i += 1) each_blocks[i].r();
				each_blocks = update_keyed_each(each_blocks, dirty, get_key, 1, ctx, each_value, each_1_lookup, div1, fix_and_outro_and_destroy_block, create_each_block, null, get_each_context);
				for (let i = 0; i < each_blocks.length; i += 1) each_blocks[i].a();
				check_outros();
			}
		},
		i(local) {
			if (current) return;

			for (let i = 0; i < each_value.length; i += 1) {
				transition_in(each_blocks[i]);
			}

			current = true;
		},
		o(local) {
			for (let i = 0; i < each_blocks.length; i += 1) {
				transition_out(each_blocks[i]);
			}

			current = false;
		},
		d(detaching) {
			if (detaching) detach(main);
			/*div0_binding*/ ctx[24](null);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].d();
			}

			mounted = false;
			run_all(dispose);
		}
	};
}

// (99:49) 
function create_if_block_5(ctx) {
	let input;
	let span;
	let t;
	let mounted;
	let dispose;

	return {
		c() {
			input = element("input");
			span = element("span");
			t = text(/*field*/ ctx[0]);
			this.h();
		},
		l(nodes) {
			input = claim_element(nodes, "INPUT", { id: true, type: true, class: true });
			span = claim_element(nodes, "SPAN", {});
			var span_nodes = children(span);
			t = claim_text(span_nodes, /*field*/ ctx[0]);
			span_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(input, "id", /*label*/ ctx[1]);
			attr(input, "type", "checkbox");
			attr(input, "class", "svelte-1dgf7zq");
		},
		m(target, anchor) {
			insert(target, input, anchor);
			input.checked = /*field*/ ctx[0];
			insert(target, span, anchor);
			append(span, t);

			if (!mounted) {
				dispose = listen(input, "change", /*input_change_handler*/ ctx[23]);
				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (dirty[0] & /*label*/ 2) {
				attr(input, "id", /*label*/ ctx[1]);
			}

			if (dirty[0] & /*field*/ 1) {
				input.checked = /*field*/ ctx[0];
			}

			if (dirty[0] & /*field*/ 1) set_data(t, /*field*/ ctx[0]);
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(input);
			if (detaching) detach(span);
			mounted = false;
			dispose();
		}
	};
}

// (91:47) 
function create_if_block_2(ctx) {
	let show_if;
	let if_block_anchor;

	function select_block_type_1(ctx, dirty) {
		if (show_if == null || dirty[0] & /*field*/ 1) show_if = !!isDate(/*field*/ ctx[0]);
		if (show_if) return create_if_block_3;
		if (/*field*/ ctx[0].length < 50) return create_if_block_4;
		return create_else_block;
	}

	let current_block_type = select_block_type_1(ctx, [-1, -1]);
	let if_block = current_block_type(ctx);

	return {
		c() {
			if_block.c();
			if_block_anchor = empty();
		},
		l(nodes) {
			if_block.l(nodes);
			if_block_anchor = empty();
		},
		m(target, anchor) {
			if_block.m(target, anchor);
			insert(target, if_block_anchor, anchor);
		},
		p(ctx, dirty) {
			if (current_block_type === (current_block_type = select_block_type_1(ctx, dirty)) && if_block) {
				if_block.p(ctx, dirty);
			} else {
				if_block.d(1);
				if_block = current_block_type(ctx);

				if (if_block) {
					if_block.c();
					if_block.m(if_block_anchor.parentNode, if_block_anchor);
				}
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if_block.d(detaching);
			if (detaching) detach(if_block_anchor);
		}
	};
}

// (89:30) 
function create_if_block_1(ctx) {
	let div;
	let t0;
	let t1;

	return {
		c() {
			div = element("div");
			t0 = text(/*field*/ ctx[0]);
			t1 = text(" is undefined");
		},
		l(nodes) {
			div = claim_element(nodes, "DIV", {});
			var div_nodes = children(div);
			t0 = claim_text(div_nodes, /*field*/ ctx[0]);
			t1 = claim_text(div_nodes, " is undefined");
			div_nodes.forEach(detach);
		},
		m(target, anchor) {
			insert(target, div, anchor);
			append(div, t0);
			append(div, t1);
		},
		p(ctx, dirty) {
			if (dirty[0] & /*field*/ 1) set_data(t0, /*field*/ ctx[0]);
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div);
		}
	};
}

// (87:0) {#if field === null}
function create_if_block(ctx) {
	let div;
	let t0;
	let t1;

	return {
		c() {
			div = element("div");
			t0 = text(/*field*/ ctx[0]);
			t1 = text(" is null");
		},
		l(nodes) {
			div = claim_element(nodes, "DIV", {});
			var div_nodes = children(div);
			t0 = claim_text(div_nodes, /*field*/ ctx[0]);
			t1 = claim_text(div_nodes, " is null");
			div_nodes.forEach(detach);
		},
		m(target, anchor) {
			insert(target, div, anchor);
			append(div, t0);
			append(div, t1);
		},
		p(ctx, dirty) {
			if (dirty[0] & /*field*/ 1) set_data(t0, /*field*/ ctx[0]);
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div);
		}
	};
}

// (187:8) {#each Object.entries(field) as [key, value]}
function create_each_block_1(ctx) {
	let div;
	let label_1;
	let t0_value = /*key*/ ctx[41] + "";
	let t0;
	let label_1_for_value;
	let t1;
	let component;
	let updating_field;
	let t2;
	let current;

	function component_field_binding_1(value) {
		/*component_field_binding_1*/ ctx[37](value, /*key*/ ctx[41]);
	}

	let component_props = { label: /*key*/ ctx[41] };

	if (/*field*/ ctx[0][/*key*/ ctx[41]] !== void 0) {
		component_props.field = /*field*/ ctx[0][/*key*/ ctx[41]];
	}

	component = new Component({ props: component_props });
	binding_callbacks.push(() => bind(component, "field", component_field_binding_1));

	return {
		c() {
			div = element("div");
			label_1 = element("label");
			t0 = text(t0_value);
			t1 = space();
			create_component(component.$$.fragment);
			t2 = space();
			this.h();
		},
		l(nodes) {
			div = claim_element(nodes, "DIV", {});
			var div_nodes = children(div);
			label_1 = claim_element(div_nodes, "LABEL", { for: true, class: true });
			var label_1_nodes = children(label_1);
			t0 = claim_text(label_1_nodes, t0_value);
			label_1_nodes.forEach(detach);
			t1 = claim_space(div_nodes);
			claim_component(component.$$.fragment, div_nodes);
			t2 = claim_space(div_nodes);
			div_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(label_1, "for", label_1_for_value = /*key*/ ctx[41]);
			attr(label_1, "class", "svelte-1dgf7zq");
		},
		m(target, anchor) {
			insert(target, div, anchor);
			append(div, label_1);
			append(label_1, t0);
			append(div, t1);
			mount_component(component, div, null);
			append(div, t2);
			current = true;
		},
		p(new_ctx, dirty) {
			ctx = new_ctx;
			if ((!current || dirty[0] & /*field*/ 1) && t0_value !== (t0_value = /*key*/ ctx[41] + "")) set_data(t0, t0_value);

			if (!current || dirty[0] & /*field*/ 1 && label_1_for_value !== (label_1_for_value = /*key*/ ctx[41])) {
				attr(label_1, "for", label_1_for_value);
			}

			const component_changes = {};
			if (dirty[0] & /*field*/ 1) component_changes.label = /*key*/ ctx[41];

			if (!updating_field && dirty[0] & /*field*/ 1) {
				updating_field = true;
				component_changes.field = /*field*/ ctx[0][/*key*/ ctx[41]];
				add_flush_callback(() => updating_field = false);
			}

			component.$set(component_changes);
		},
		i(local) {
			if (current) return;
			transition_in(component.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(component.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(div);
			destroy_component(component);
		}
	};
}

// (161:20) {:else}
function create_else_block_1(ctx) {
	let t0;
	let t1_value = /*key*/ ctx[41] + "";
	let t1;

	return {
		c() {
			t0 = text("Component ");
			t1 = text(t1_value);
		},
		l(nodes) {
			t0 = claim_text(nodes, "Component ");
			t1 = claim_text(nodes, t1_value);
		},
		m(target, anchor) {
			insert(target, t0, anchor);
			insert(target, t1, anchor);
		},
		p(ctx, dirty) {
			if (dirty[0] & /*field*/ 1 && t1_value !== (t1_value = /*key*/ ctx[41] + "")) set_data(t1, t1_value);
		},
		d(detaching) {
			if (detaching) detach(t0);
			if (detaching) detach(t1);
		}
	};
}

// (159:69) 
function create_if_block_10(ctx) {
	let t_value = (Object.values(/*value*/ ctx[39])[0].constructor === ("").constructor
	? Object.values(/*value*/ ctx[39])[0].replace(/<[^>]*>?/gm, "").slice(0, 20).concat(/*value*/ ctx[39].length > 20 ? "..." : "")
	: Object.keys(/*value*/ ctx[39])[0]) + "";

	let t;

	return {
		c() {
			t = text(t_value);
		},
		l(nodes) {
			t = claim_text(nodes, t_value);
		},
		m(target, anchor) {
			insert(target, t, anchor);
		},
		p(ctx, dirty) {
			if (dirty[0] & /*field*/ 1 && t_value !== (t_value = (Object.values(/*value*/ ctx[39])[0].constructor === ("").constructor
			? Object.values(/*value*/ ctx[39])[0].replace(/<[^>]*>?/gm, "").slice(0, 20).concat(/*value*/ ctx[39].length > 20 ? "..." : "")
			: Object.keys(/*value*/ ctx[39])[0]) + "")) set_data(t, t_value);
		},
		d(detaching) {
			if (detaching) detach(t);
		}
	};
}

// (157:20) {#if value.constructor === "".constructor}
function create_if_block_9(ctx) {
	let t_value = /*value*/ ctx[39].replace(/<[^>]*>?/gm, "").slice(0, 20).concat(/*value*/ ctx[39].length > 20 ? "..." : "") + "";
	let t;

	return {
		c() {
			t = text(t_value);
		},
		l(nodes) {
			t = claim_text(nodes, t_value);
		},
		m(target, anchor) {
			insert(target, t, anchor);
		},
		p(ctx, dirty) {
			if (dirty[0] & /*field*/ 1 && t_value !== (t_value = /*value*/ ctx[39].replace(/<[^>]*>?/gm, "").slice(0, 20).concat(/*value*/ ctx[39].length > 20 ? "..." : "") + "")) set_data(t, t_value);
		},
		d(detaching) {
			if (detaching) detach(t);
		}
	};
}

// (167:20) {#if removesItems}
function create_if_block_8(ctx) {
	let button;
	let svg;
	let path0;
	let path1;
	let mounted;
	let dispose;

	function click_handler_2() {
		return /*click_handler_2*/ ctx[31](/*value*/ ctx[39]);
	}

	return {
		c() {
			button = element("button");
			svg = svg_element("svg");
			path0 = svg_element("path");
			path1 = svg_element("path");
			this.h();
		},
		l(nodes) {
			button = claim_element(nodes, "BUTTON", { class: true });
			var button_nodes = children(button);

			svg = claim_element(
				button_nodes,
				"svg",
				{
					xmlns: true,
					height: true,
					viewBox: true,
					width: true
				},
				1
			);

			var svg_nodes = children(svg);
			path0 = claim_element(svg_nodes, "path", { d: true, fill: true }, 1);
			children(path0).forEach(detach);
			path1 = claim_element(svg_nodes, "path", { d: true }, 1);
			children(path1).forEach(detach);
			svg_nodes.forEach(detach);
			button_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(path0, "d", "M0 0h24v24H0z");
			attr(path0, "fill", "none");
			attr(path1, "d", "M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z");
			attr(svg, "xmlns", "http://www.w3.org/2000/svg");
			attr(svg, "height", "16");
			attr(svg, "viewBox", "0 0 24 24");
			attr(svg, "width", "16");
			attr(button, "class", "svelte-1dgf7zq");
		},
		m(target, anchor) {
			insert(target, button, anchor);
			append(button, svg);
			append(svg, path0);
			append(svg, path1);

			if (!mounted) {
				dispose = listen(button, "click", prevent_default(click_handler_2));
				mounted = true;
			}
		},
		p(new_ctx, dirty) {
			ctx = new_ctx;
		},
		d(detaching) {
			if (detaching) detach(button);
			mounted = false;
			dispose();
		}
	};
}

// (175:12) {#if openKeys.includes(key)}
function create_if_block_7(ctx) {
	let div;
	let component;
	let updating_field;
	let div_transition;
	let current;

	function component_field_binding(value) {
		/*component_field_binding*/ ctx[32](value, /*key*/ ctx[41]);
	}

	let component_props = { label: /*label*/ ctx[1] };

	if (/*field*/ ctx[0][/*key*/ ctx[41]] !== void 0) {
		component_props.field = /*field*/ ctx[0][/*key*/ ctx[41]];
	}

	component = new Component({ props: component_props });
	binding_callbacks.push(() => bind(component, "field", component_field_binding));

	return {
		c() {
			div = element("div");
			create_component(component.$$.fragment);
		},
		l(nodes) {
			div = claim_element(nodes, "DIV", {});
			var div_nodes = children(div);
			claim_component(component.$$.fragment, div_nodes);
			div_nodes.forEach(detach);
		},
		m(target, anchor) {
			insert(target, div, anchor);
			mount_component(component, div, null);
			current = true;
		},
		p(new_ctx, dirty) {
			ctx = new_ctx;
			const component_changes = {};
			if (dirty[0] & /*label*/ 2) component_changes.label = /*label*/ ctx[1];

			if (!updating_field && dirty[0] & /*field*/ 1) {
				updating_field = true;
				component_changes.field = /*field*/ ctx[0][/*key*/ ctx[41]];
				add_flush_callback(() => updating_field = false);
			}

			component.$set(component_changes);
		},
		i(local) {
			if (current) return;
			transition_in(component.$$.fragment, local);

			add_render_callback(() => {
				if (!div_transition) div_transition = create_bidirectional_transition(div, slide, { duration: 300 }, true);
				div_transition.run(1);
			});

			current = true;
		},
		o(local) {
			transition_out(component.$$.fragment, local);
			if (!div_transition) div_transition = create_bidirectional_transition(div, slide, { duration: 300 }, false);
			div_transition.run(0);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(div);
			destroy_component(component);
			if (detaching && div_transition) div_transition.end();
		}
	};
}

// (114:8) {#each field as value, key (compID = isOpen ? key : value.constructor === ({}
function create_each_block(key_2, ctx) {
	let div5;
	let div4;
	let div0;
	let svg0;
	let path0;
	let circle0;
	let circle1;
	let circle2;
	let circle3;
	let circle4;
	let circle5;
	let t0;
	let div1;
	let button0;
	let svg1;
	let path1;
	let path2;
	let button0_style_value;
	let t1;
	let button1;
	let svg2;
	let path3;
	let path4;
	let button1_style_value;
	let t2;
	let div2;
	let t3;
	let div3;
	let t4;
	let show_if = /*openKeys*/ ctx[4].includes(/*key*/ ctx[41]);
	let t5;
	let div5_id_value;
	let div5_data_index_value;
	let rect;
	let stop_animation = noop;
	let current;
	let mounted;
	let dispose;

	function click_handler(...args) {
		return /*click_handler*/ ctx[29](/*key*/ ctx[41], ...args);
	}

	function click_handler_1(...args) {
		return /*click_handler_1*/ ctx[30](/*key*/ ctx[41], ...args);
	}

	function select_block_type_2(ctx, dirty) {
		if (/*value*/ ctx[39].constructor === ("").constructor) return create_if_block_9;
		if (/*value*/ ctx[39].constructor === ({}).constructor) return create_if_block_10;
		return create_else_block_1;
	}

	let current_block_type = select_block_type_2(ctx, [-1, -1]);
	let if_block0 = current_block_type(ctx);
	let if_block1 = /*removesItems*/ ctx[2] && create_if_block_8(ctx);
	let if_block2 = show_if && create_if_block_7(ctx);

	return {
		key: key_2,
		first: null,
		c() {
			div5 = element("div");
			div4 = element("div");
			div0 = element("div");
			svg0 = svg_element("svg");
			path0 = svg_element("path");
			circle0 = svg_element("circle");
			circle1 = svg_element("circle");
			circle2 = svg_element("circle");
			circle3 = svg_element("circle");
			circle4 = svg_element("circle");
			circle5 = svg_element("circle");
			t0 = space();
			div1 = element("div");
			button0 = element("button");
			svg1 = svg_element("svg");
			path1 = svg_element("path");
			path2 = svg_element("path");
			t1 = space();
			button1 = element("button");
			svg2 = svg_element("svg");
			path3 = svg_element("path");
			path4 = svg_element("path");
			t2 = space();
			div2 = element("div");
			if_block0.c();
			t3 = space();
			div3 = element("div");
			if (if_block1) if_block1.c();
			t4 = space();
			if (if_block2) if_block2.c();
			t5 = space();
			this.h();
		},
		l(nodes) {
			div5 = claim_element(nodes, "DIV", {
				id: true,
				"data-index": true,
				"data-id": true,
				"data-graby": true,
				class: true
			});

			var div5_nodes = children(div5);
			div4 = claim_element(div5_nodes, "DIV", { class: true });
			var div4_nodes = children(div4);
			div0 = claim_element(div4_nodes, "DIV", { class: true });
			var div0_nodes = children(div0);

			svg0 = claim_element(
				div0_nodes,
				"svg",
				{
					xmlns: true,
					class: true,
					width: true,
					height: true,
					viewBox: true,
					"stroke-width": true,
					stroke: true,
					fill: true,
					"stroke-linecap": true,
					"stroke-linejoin": true
				},
				1
			);

			var svg0_nodes = children(svg0);
			path0 = claim_element(svg0_nodes, "path", { stroke: true, d: true, fill: true }, 1);
			children(path0).forEach(detach);
			circle0 = claim_element(svg0_nodes, "circle", { cx: true, cy: true, r: true }, 1);
			children(circle0).forEach(detach);
			circle1 = claim_element(svg0_nodes, "circle", { cx: true, cy: true, r: true }, 1);
			children(circle1).forEach(detach);
			circle2 = claim_element(svg0_nodes, "circle", { cx: true, cy: true, r: true }, 1);
			children(circle2).forEach(detach);
			circle3 = claim_element(svg0_nodes, "circle", { cx: true, cy: true, r: true }, 1);
			children(circle3).forEach(detach);
			circle4 = claim_element(svg0_nodes, "circle", { cx: true, cy: true, r: true }, 1);
			children(circle4).forEach(detach);
			circle5 = claim_element(svg0_nodes, "circle", { cx: true, cy: true, r: true }, 1);
			children(circle5).forEach(detach);
			svg0_nodes.forEach(detach);
			div0_nodes.forEach(detach);
			t0 = claim_space(div4_nodes);
			div1 = claim_element(div4_nodes, "DIV", { class: true });
			var div1_nodes = children(div1);
			button0 = claim_element(div1_nodes, "BUTTON", { class: true, style: true });
			var button0_nodes = children(button0);

			svg1 = claim_element(
				button0_nodes,
				"svg",
				{
					xmlns: true,
					viewBox: true,
					width: true,
					height: true
				},
				1
			);

			var svg1_nodes = children(svg1);
			path1 = claim_element(svg1_nodes, "path", { d: true, fill: true }, 1);
			children(path1).forEach(detach);
			path2 = claim_element(svg1_nodes, "path", { d: true }, 1);
			children(path2).forEach(detach);
			svg1_nodes.forEach(detach);
			button0_nodes.forEach(detach);
			t1 = claim_space(div1_nodes);
			button1 = claim_element(div1_nodes, "BUTTON", { class: true, style: true });
			var button1_nodes = children(button1);

			svg2 = claim_element(
				button1_nodes,
				"svg",
				{
					xmlns: true,
					viewBox: true,
					width: true,
					height: true
				},
				1
			);

			var svg2_nodes = children(svg2);
			path3 = claim_element(svg2_nodes, "path", { d: true, fill: true }, 1);
			children(path3).forEach(detach);
			path4 = claim_element(svg2_nodes, "path", { d: true }, 1);
			children(path4).forEach(detach);
			svg2_nodes.forEach(detach);
			button1_nodes.forEach(detach);
			div1_nodes.forEach(detach);
			t2 = claim_space(div4_nodes);
			div2 = claim_element(div4_nodes, "DIV", { class: true });
			var div2_nodes = children(div2);
			if_block0.l(div2_nodes);
			div2_nodes.forEach(detach);
			t3 = claim_space(div4_nodes);
			div3 = claim_element(div4_nodes, "DIV", { class: true });
			var div3_nodes = children(div3);
			if (if_block1) if_block1.l(div3_nodes);
			div3_nodes.forEach(detach);
			div4_nodes.forEach(detach);
			t4 = claim_space(div5_nodes);
			if (if_block2) if_block2.l(div5_nodes);
			t5 = claim_space(div5_nodes);
			div5_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(path0, "stroke", "none");
			attr(path0, "d", "M0 0h24v24H0z");
			attr(path0, "fill", "none");
			attr(circle0, "cx", "5");
			attr(circle0, "cy", "9");
			attr(circle0, "r", "1");
			attr(circle1, "cx", "5");
			attr(circle1, "cy", "15");
			attr(circle1, "r", "1");
			attr(circle2, "cx", "12");
			attr(circle2, "cy", "9");
			attr(circle2, "r", "1");
			attr(circle3, "cx", "12");
			attr(circle3, "cy", "15");
			attr(circle3, "r", "1");
			attr(circle4, "cx", "19");
			attr(circle4, "cy", "9");
			attr(circle4, "r", "1");
			attr(circle5, "cx", "19");
			attr(circle5, "cy", "15");
			attr(circle5, "r", "1");
			attr(svg0, "xmlns", "http://www.w3.org/2000/svg");
			attr(svg0, "class", "icon icon-tabler icon-tabler-grip-horizontal");
			attr(svg0, "width", "30");
			attr(svg0, "height", "30");
			attr(svg0, "viewBox", "0 0 24 24");
			attr(svg0, "stroke-width", "1.5");
			attr(svg0, "stroke", "#2c3e50");
			attr(svg0, "fill", "none");
			attr(svg0, "stroke-linecap", "round");
			attr(svg0, "stroke-linejoin", "round");
			attr(div0, "class", "grip svelte-1dgf7zq");
			attr(path1, "d", "M0 0h24v24H0V0z");
			attr(path1, "fill", "none");
			attr(path2, "d", "M7.41 15.41L12 10.83l4.59 4.58L18 14l-6-6-6 6 1.41 1.41z");
			attr(svg1, "xmlns", "http://www.w3.org/2000/svg");
			attr(svg1, "viewBox", "0 0 24 24");
			attr(svg1, "width", "16px");
			attr(svg1, "height", "16px");
			attr(button0, "class", "up svelte-1dgf7zq");
			attr(button0, "style", button0_style_value = "visibility: " + (/*key*/ ctx[41] > 0 ? "" : "hidden") + ";");
			attr(path3, "d", "M0 0h24v24H0V0z");
			attr(path3, "fill", "none");
			attr(path4, "d", "M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6-6-6 1.41-1.41z");
			attr(svg2, "xmlns", "http://www.w3.org/2000/svg");
			attr(svg2, "viewBox", "0 0 24 24");
			attr(svg2, "width", "16px");
			attr(svg2, "height", "16px");
			attr(button1, "class", "down svelte-1dgf7zq");

			attr(button1, "style", button1_style_value = "visibility: " + (/*key*/ ctx[41] < /*field*/ ctx[0].length - 1
			? ""
			: "hidden") + ";");

			attr(div1, "class", "buttons svelte-1dgf7zq");
			attr(div2, "class", "content svelte-1dgf7zq");
			attr(div3, "class", "buttons svelte-1dgf7zq");
			attr(div4, "class", "item svelte-1dgf7zq");

			attr(div5, "id", div5_id_value = /*grabbed*/ ctx[6] && /*compID*/ ctx[12] == /*grabbed*/ ctx[6].dataset.id
			? "grabbed"
			: "");

			attr(div5, "data-index", div5_data_index_value = /*key*/ ctx[41]);
			attr(div5, "data-id", /*compID*/ ctx[12]);
			attr(div5, "data-graby", "0");
			attr(div5, "class", "item-wrapper svelte-1dgf7zq");
			this.first = div5;
		},
		m(target, anchor) {
			insert(target, div5, anchor);
			append(div5, div4);
			append(div4, div0);
			append(div0, svg0);
			append(svg0, path0);
			append(svg0, circle0);
			append(svg0, circle1);
			append(svg0, circle2);
			append(svg0, circle3);
			append(svg0, circle4);
			append(svg0, circle5);
			append(div4, t0);
			append(div4, div1);
			append(div1, button0);
			append(button0, svg1);
			append(svg1, path1);
			append(svg1, path2);
			append(div1, t1);
			append(div1, button1);
			append(button1, svg2);
			append(svg2, path3);
			append(svg2, path4);
			append(div4, t2);
			append(div4, div2);
			if_block0.m(div2, null);
			append(div4, t3);
			append(div4, div3);
			if (if_block1) if_block1.m(div3, null);
			append(div5, t4);
			if (if_block2) if_block2.m(div5, null);
			append(div5, t5);
			current = true;

			if (!mounted) {
				dispose = [
					listen(div0, "mousedown", /*mousedown_handler*/ ctx[25]),
					listen(div0, "touchstart", /*touchstart_handler*/ ctx[26]),
					listen(div0, "mouseenter", /*mouseenter_handler*/ ctx[27]),
					listen(div0, "touchmove", /*touchmove_handler*/ ctx[28]),
					listen(button0, "click", prevent_default(click_handler)),
					listen(button1, "click", prevent_default(click_handler_1)),
					listen(div2, "click", prevent_default(function () {
						if (is_function(/*accordion*/ ctx[11](/*key*/ ctx[41]))) /*accordion*/ ctx[11](/*key*/ ctx[41]).apply(this, arguments);
					}))
				];

				mounted = true;
			}
		},
		p(new_ctx, dirty) {
			ctx = new_ctx;

			if (!current || dirty[0] & /*field*/ 1 && button0_style_value !== (button0_style_value = "visibility: " + (/*key*/ ctx[41] > 0 ? "" : "hidden") + ";")) {
				attr(button0, "style", button0_style_value);
			}

			if (!current || dirty[0] & /*field*/ 1 && button1_style_value !== (button1_style_value = "visibility: " + (/*key*/ ctx[41] < /*field*/ ctx[0].length - 1
			? ""
			: "hidden") + ";")) {
				attr(button1, "style", button1_style_value);
			}

			if (current_block_type === (current_block_type = select_block_type_2(ctx, dirty)) && if_block0) {
				if_block0.p(ctx, dirty);
			} else {
				if_block0.d(1);
				if_block0 = current_block_type(ctx);

				if (if_block0) {
					if_block0.c();
					if_block0.m(div2, null);
				}
			}

			if (/*removesItems*/ ctx[2]) {
				if (if_block1) {
					if_block1.p(ctx, dirty);
				} else {
					if_block1 = create_if_block_8(ctx);
					if_block1.c();
					if_block1.m(div3, null);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (dirty[0] & /*openKeys, field*/ 17) show_if = /*openKeys*/ ctx[4].includes(/*key*/ ctx[41]);

			if (show_if) {
				if (if_block2) {
					if_block2.p(ctx, dirty);

					if (dirty[0] & /*openKeys, field*/ 17) {
						transition_in(if_block2, 1);
					}
				} else {
					if_block2 = create_if_block_7(ctx);
					if_block2.c();
					transition_in(if_block2, 1);
					if_block2.m(div5, t5);
				}
			} else if (if_block2) {
				group_outros();

				transition_out(if_block2, 1, 1, () => {
					if_block2 = null;
				});

				check_outros();
			}

			if (!current || dirty[0] & /*grabbed*/ 64 && div5_id_value !== (div5_id_value = /*grabbed*/ ctx[6] && /*compID*/ ctx[12] == /*grabbed*/ ctx[6].dataset.id
			? "grabbed"
			: "")) {
				attr(div5, "id", div5_id_value);
			}

			if (!current || dirty[0] & /*field*/ 1 && div5_data_index_value !== (div5_data_index_value = /*key*/ ctx[41])) {
				attr(div5, "data-index", div5_data_index_value);
			}
		},
		r() {
			rect = div5.getBoundingClientRect();
		},
		f() {
			fix_position(div5);
			stop_animation();
		},
		a() {
			stop_animation();
			stop_animation = create_animation(div5, rect, flip, { duration: /*isOpen*/ ctx[3] ? null : 200 });
		},
		i(local) {
			if (current) return;
			transition_in(if_block2);
			current = true;
		},
		o(local) {
			transition_out(if_block2);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(div5);
			if_block0.d();
			if (if_block1) if_block1.d();
			if (if_block2) if_block2.d();
			mounted = false;
			run_all(dispose);
		}
	};
}

// (96:4) {:else}
function create_else_block(ctx) {
	let textarea;
	let mounted;
	let dispose;

	return {
		c() {
			textarea = element("textarea");
			this.h();
		},
		l(nodes) {
			textarea = claim_element(nodes, "TEXTAREA", { id: true, rows: true, class: true });
			children(textarea).forEach(detach);
			this.h();
		},
		h() {
			attr(textarea, "id", /*label*/ ctx[1]);
			attr(textarea, "rows", "5");
			attr(textarea, "class", "svelte-1dgf7zq");
		},
		m(target, anchor) {
			insert(target, textarea, anchor);
			set_input_value(textarea, /*field*/ ctx[0]);

			if (!mounted) {
				dispose = listen(textarea, "input", /*textarea_input_handler*/ ctx[22]);
				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (dirty[0] & /*label*/ 2) {
				attr(textarea, "id", /*label*/ ctx[1]);
			}

			if (dirty[0] & /*field*/ 1) {
				set_input_value(textarea, /*field*/ ctx[0]);
			}
		},
		d(detaching) {
			if (detaching) detach(textarea);
			mounted = false;
			dispose();
		}
	};
}

// (94:32) 
function create_if_block_4(ctx) {
	let input;
	let mounted;
	let dispose;

	return {
		c() {
			input = element("input");
			this.h();
		},
		l(nodes) {
			input = claim_element(nodes, "INPUT", { id: true, type: true, class: true });
			this.h();
		},
		h() {
			attr(input, "id", /*label*/ ctx[1]);
			attr(input, "type", "text");
			attr(input, "class", "svelte-1dgf7zq");
		},
		m(target, anchor) {
			insert(target, input, anchor);
			set_input_value(input, /*field*/ ctx[0]);

			if (!mounted) {
				dispose = listen(input, "input", /*input_input_handler*/ ctx[21]);
				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (dirty[0] & /*label*/ 2) {
				attr(input, "id", /*label*/ ctx[1]);
			}

			if (dirty[0] & /*field*/ 1 && input.value !== /*field*/ ctx[0]) {
				set_input_value(input, /*field*/ ctx[0]);
			}
		},
		d(detaching) {
			if (detaching) detach(input);
			mounted = false;
			dispose();
		}
	};
}

// (92:4) {#if isDate(field)}
function create_if_block_3(ctx) {
	let input;
	let input_value_value;
	let mounted;
	let dispose;

	return {
		c() {
			input = element("input");
			this.h();
		},
		l(nodes) {
			input = claim_element(nodes, "INPUT", { type: true });
			this.h();
		},
		h() {
			attr(input, "type", "date");
			input.value = input_value_value = makeDate(/*field*/ ctx[0]);
		},
		m(target, anchor) {
			insert(target, input, anchor);

			if (!mounted) {
				dispose = listen(input, "input", /*input_handler*/ ctx[20]);
				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (dirty[0] & /*field*/ 1 && input_value_value !== (input_value_value = makeDate(/*field*/ ctx[0]))) {
				input.value = input_value_value;
			}
		},
		d(detaching) {
			if (detaching) detach(input);
			mounted = false;
			dispose();
		}
	};
}

function create_fragment(ctx) {
	let current_block_type_index;
	let if_block;
	let if_block_anchor;
	let current;

	const if_block_creators = [
		create_if_block,
		create_if_block_1,
		create_if_block_2,
		create_if_block_5,
		create_if_block_6,
		create_if_block_11
	];

	const if_blocks = [];

	function select_block_type(ctx, dirty) {
		if (/*field*/ ctx[0] === null) return 0;
		if (/*field*/ ctx[0] === undefined) return 1;
		if (/*field*/ ctx[0].constructor === ("").constructor) return 2;
		if (/*field*/ ctx[0].constructor === (true).constructor) return 3;
		if (/*field*/ ctx[0].constructor === [].constructor) return 4;
		if (/*field*/ ctx[0].constructor === ({}).constructor) return 5;
		return -1;
	}

	if (~(current_block_type_index = select_block_type(ctx, [-1, -1]))) {
		if_block = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);
	}

	return {
		c() {
			if (if_block) if_block.c();
			if_block_anchor = empty();
		},
		l(nodes) {
			if (if_block) if_block.l(nodes);
			if_block_anchor = empty();
		},
		m(target, anchor) {
			if (~current_block_type_index) {
				if_blocks[current_block_type_index].m(target, anchor);
			}

			insert(target, if_block_anchor, anchor);
			current = true;
		},
		p(ctx, dirty) {
			let previous_block_index = current_block_type_index;
			current_block_type_index = select_block_type(ctx, dirty);

			if (current_block_type_index === previous_block_index) {
				if (~current_block_type_index) {
					if_blocks[current_block_type_index].p(ctx, dirty);
				}
			} else {
				if (if_block) {
					group_outros();

					transition_out(if_blocks[previous_block_index], 1, 1, () => {
						if_blocks[previous_block_index] = null;
					});

					check_outros();
				}

				if (~current_block_type_index) {
					if_block = if_blocks[current_block_type_index];

					if (!if_block) {
						if_block = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);
						if_block.c();
					} else {
						if_block.p(ctx, dirty);
					}

					transition_in(if_block, 1);
					if_block.m(if_block_anchor.parentNode, if_block_anchor);
				} else {
					if_block = null;
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(if_block);
			current = true;
		},
		o(local) {
			transition_out(if_block);
			current = false;
		},
		d(detaching) {
			if (~current_block_type_index) {
				if_blocks[current_block_type_index].d(detaching);
			}

			if (detaching) detach(if_block_anchor);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { field } = $$props, { label } = $$props;

	const bindDate = date => {
		$$invalidate(0, field = formatDate(date, field));
	};

	let isOpen = false;
	let openKeys = [];

	const accordion = newKey => {
		if (openKeys.length === 1 && openKeys.includes(newKey)) {
			setTimeout(
				() => {
					$$invalidate(3, isOpen = false);
				},
				300
			);
		}

		if (openKeys.includes(newKey)) {
			// Remove key
			$$invalidate(4, openKeys = openKeys.filter(key => key !== newKey));
		} else {
			// Add key
			$$invalidate(4, openKeys = [...openKeys, newKey]);

			$$invalidate(3, isOpen = true);
		}
	};

	let { removesItems = true } = $$props;
	let compID;
	let ghost;
	let grabbed;
	let lastTarget;
	let mouseY = 0; // pointer y coordinate within client
	let offsetY = 0; // y distance from top of grabbed element to pointer
	let layerY = 0; // distance from top of list to top of client

	const grab = (clientY, element) => {
		// modify grabbed element
		$$invalidate(6, grabbed = element);

		$$invalidate(6, grabbed.dataset.grabY = clientY, grabbed);

		// modify ghost element (which is actually dragged)
		$$invalidate(5, ghost.innerHTML = grabbed.innerHTML, ghost);

		// record offset from cursor to top of element
		// (used for positioning ghost)
		$$invalidate(8, offsetY = grabbed.getBoundingClientRect().y - clientY);

		drag(clientY);
	};

	// drag handler updates cursor position
	const drag = clientY => {
		if (grabbed) {
			$$invalidate(7, mouseY = clientY);
			$$invalidate(9, layerY = ghost.parentNode.getBoundingClientRect().y);
		}
	};

	// touchEnter handler emulates the mouseenter event for touch input
	const touchEnter = ev => {
		drag(ev.clientY);

		// trigger dragEnter the first time the cursor moves over a list item
		let target = document.elementFromPoint(ev.clientX, ev.clientY).closest(".item-wrapper");

		if (target && target != lastTarget) {
			lastTarget = target;
			dragEnter(ev, target);
		}
	};

	const dragEnter = (ev, target) => {
		// swap items
		if (grabbed && target != grabbed && target.classList.contains("item-wrapper")) {
			moveItem(parseInt(grabbed.dataset.index), parseInt(target.dataset.index));
		}
	};

	// does the actual moving of items
	const moveItem = (from, to) => {
		let temp = field[from];
		$$invalidate(0, field[from] = field[to], field);
		$$invalidate(0, field[to] = temp, field);
	};

	const release = ev => {
		$$invalidate(6, grabbed = null);
	};

	const removeItem = val => {
		$$invalidate(0, field = field.filter(i => i !== val));
	};

	const input_handler = date => bindDate(date.target.value);

	function input_input_handler() {
		field = this.value;
		$$invalidate(0, field);
	}

	function textarea_input_handler() {
		field = this.value;
		$$invalidate(0, field);
	}

	function input_change_handler() {
		field = this.checked;
		$$invalidate(0, field);
	}

	function div0_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			ghost = $$value;
			$$invalidate(5, ghost);
		});
	}

	const mousedown_handler = function (ev) {
		grab(ev.clientY, this.closest(".item-wrapper"));
	};

	const touchstart_handler = function (ev) {
		grab(ev.touches[0].clientY, this.closest(".item-wrapper"));
	};

	const mouseenter_handler = function (ev) {
		ev.stopPropagation();
		dragEnter(ev, ev.target.closest(".item-wrapper"));
	};

	const touchmove_handler = function (ev) {
		ev.stopPropagation();
		ev.preventDefault();
		touchEnter(ev.touches[0]);
	};

	const click_handler = function (key, ev) {
		moveItem(key, key - 1);
	};

	const click_handler_1 = function (key, ev) {
		moveItem(key, key + 1);
	};

	const click_handler_2 = value => removeItem(value);

	function component_field_binding(value, key) {
		if ($$self.$$.not_equal(field[key], value)) {
			field[key] = value;
			$$invalidate(0, field);
		}
	}

	const mousemove_handler = function (ev) {
		ev.stopPropagation();
		drag(ev.clientY);
	};

	const touchmove_handler_1 = function (ev) {
		ev.stopPropagation();
		drag(ev.touches[0].clientY);
	};

	const mouseup_handler = function (ev) {
		ev.stopPropagation();
		release(ev);
	};

	const touchend_handler = function (ev) {
		ev.stopPropagation();
		release(ev.touches[0]);
	};

	function component_field_binding_1(value, key) {
		if ($$self.$$.not_equal(field[key], value)) {
			field[key] = value;
			$$invalidate(0, field);
		}
	}

	$$self.$$set = $$props => {
		if ("field" in $$props) $$invalidate(0, field = $$props.field);
		if ("label" in $$props) $$invalidate(1, label = $$props.label);
		if ("removesItems" in $$props) $$invalidate(2, removesItems = $$props.removesItems);
	};

	return [
		field,
		label,
		removesItems,
		isOpen,
		openKeys,
		ghost,
		grabbed,
		mouseY,
		offsetY,
		layerY,
		bindDate,
		accordion,
		compID,
		grab,
		drag,
		touchEnter,
		dragEnter,
		moveItem,
		release,
		removeItem,
		input_handler,
		input_input_handler,
		textarea_input_handler,
		input_change_handler,
		div0_binding,
		mousedown_handler,
		touchstart_handler,
		mouseenter_handler,
		touchmove_handler,
		click_handler,
		click_handler_1,
		click_handler_2,
		component_field_binding,
		mousemove_handler,
		touchmove_handler_1,
		mouseup_handler,
		touchend_handler,
		component_field_binding_1
	];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { field: 0, label: 1, removesItems: 2 }, [-1, -1]);
	}
}

export default Component;