/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	add_flush_callback,
	append,
	attr,
	bind,
	binding_callbacks,
	bubble,
	check_outros,
	children,
	claim_component,
	claim_element,
	claim_space,
	claim_text,
	create_component,
	destroy_component,
	detach,
	element,
	empty,
	group_outros,
	init,
	insert,
	listen,
	mount_component,
	noop,
	prevent_default,
	run_all,
	safe_not_equal,
	space,
	svg_element,
	text,
	transition_in,
	transition_out
} from '../../web_modules/svelte/internal/index.mjs';

import MediaGrid from './media_grid.js';
import Buttons from './buttons/buttons.js';
import Save from './buttons/save.js';

function create_else_block_1(ctx) {
	let div2;
	let div0;
	let svg;
	let path0;
	let path1;
	let polyline;
	let line;
	let t0;
	let div1;
	let t1;
	let div2_class_value;
	let t2;
	let div3;
	let t3;
	let t4;
	let div4;
	let label;
	let input;
	let t5;
	let span;
	let mounted;
	let dispose;

	return {
		c() {
			div2 = element("div");
			div0 = element("div");
			svg = svg_element("svg");
			path0 = svg_element("path");
			path1 = svg_element("path");
			polyline = svg_element("polyline");
			line = svg_element("line");
			t0 = space();
			div1 = element("div");
			t1 = text("Drag a file here to upload");
			t2 = space();
			div3 = element("div");
			t3 = text("Or");
			t4 = space();
			div4 = element("div");
			label = element("label");
			input = element("input");
			t5 = space();
			span = element("span");
			this.h();
		},
		l(nodes) {
			div2 = claim_element(nodes, "DIV", { class: true });
			var div2_nodes = children(div2);
			div0 = claim_element(div2_nodes, "DIV", { class: true });
			var div0_nodes = children(div0);

			svg = claim_element(
				div0_nodes,
				"svg",
				{
					xmlns: true,
					class: true,
					width: true,
					height: true,
					viewBox: true,
					"stroke-width": true,
					stroke: true,
					fill: true,
					"stroke-linecap": true,
					"stroke-linejoin": true
				},
				1
			);

			var svg_nodes = children(svg);
			path0 = claim_element(svg_nodes, "path", { stroke: true, d: true, fill: true }, 1);
			children(path0).forEach(detach);
			path1 = claim_element(svg_nodes, "path", { d: true }, 1);
			children(path1).forEach(detach);
			polyline = claim_element(svg_nodes, "polyline", { points: true }, 1);
			children(polyline).forEach(detach);
			line = claim_element(svg_nodes, "line", { x1: true, y1: true, x2: true, y2: true }, 1);
			children(line).forEach(detach);
			svg_nodes.forEach(detach);
			div0_nodes.forEach(detach);
			t0 = claim_space(div2_nodes);
			div1 = claim_element(div2_nodes, "DIV", { class: true });
			var div1_nodes = children(div1);
			t1 = claim_text(div1_nodes, "Drag a file here to upload");
			div1_nodes.forEach(detach);
			div2_nodes.forEach(detach);
			t2 = claim_space(nodes);
			div3 = claim_element(nodes, "DIV", { class: true });
			var div3_nodes = children(div3);
			t3 = claim_text(div3_nodes, "Or");
			div3_nodes.forEach(detach);
			t4 = claim_space(nodes);
			div4 = claim_element(nodes, "DIV", {});
			var div4_nodes = children(div4);
			label = claim_element(div4_nodes, "LABEL", { class: true });
			var label_nodes = children(label);

			input = claim_element(label_nodes, "INPUT", {
				type: true,
				"aria-label": true,
				class: true
			});

			t5 = claim_space(label_nodes);
			span = claim_element(label_nodes, "SPAN", { class: true });
			children(span).forEach(detach);
			label_nodes.forEach(detach);
			div4_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(path0, "stroke", "none");
			attr(path0, "d", "M0 0h24v24H0z");
			attr(path0, "fill", "none");
			attr(path1, "d", "M7 18a4.6 4.4 0 0 1 0 -9a5 4.5 0 0 1 11 2h1a3.5 3.5 0 0 1 0 7h-1");
			attr(polyline, "points", "9 15 12 12 15 15");
			attr(line, "x1", "12");
			attr(line, "y1", "12");
			attr(line, "x2", "12");
			attr(line, "y2", "21");
			attr(svg, "xmlns", "http://www.w3.org/2000/svg");
			attr(svg, "class", "icon icon-tabler icon-tabler-cloud-upload");
			attr(svg, "width", "44");
			attr(svg, "height", "44");
			attr(svg, "viewBox", "0 0 24 24");
			attr(svg, "stroke-width", "1.5");
			attr(svg, "stroke", "#2c3e50");
			attr(svg, "fill", "none");
			attr(svg, "stroke-linecap", "round");
			attr(svg, "stroke-linejoin", "round");
			attr(div0, "class", "drop-icon");
			attr(div1, "class", "drop-text");
			attr(div2, "class", div2_class_value = "drop" + (/*drag*/ ctx[1] ? " active" : "") + " svelte-1t99wk2");
			attr(div3, "class", "or svelte-1t99wk2");
			attr(input, "type", "file");
			input.multiple = "multiple";
			attr(input, "aria-label", "File browser");
			attr(input, "class", "svelte-1t99wk2");
			attr(span, "class", "file-custom svelte-1t99wk2");
			attr(label, "class", "file svelte-1t99wk2");
		},
		m(target, anchor) {
			insert(target, div2, anchor);
			append(div2, div0);
			append(div0, svg);
			append(svg, path0);
			append(svg, path1);
			append(svg, polyline);
			append(svg, line);
			append(div2, t0);
			append(div2, div1);
			append(div1, t1);
			insert(target, t2, anchor);
			insert(target, div3, anchor);
			append(div3, t3);
			insert(target, t4, anchor);
			insert(target, div4, anchor);
			append(div4, label);
			append(label, input);
			append(label, t5);
			append(label, span);

			if (!mounted) {
				dispose = [
					listen(div2, "dragenter", /*toggleDrag*/ ctx[4]),
					listen(div2, "dragleave", /*toggleDrag*/ ctx[4]),
					listen(div2, "drop", prevent_default(/*drop_handler*/ ctx[12])),
					listen(div2, "dragover", prevent_default(/*dragover_handler*/ ctx[8])),
					listen(div4, "change", /*change_handler*/ ctx[13])
				];

				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (dirty & /*drag*/ 2 && div2_class_value !== (div2_class_value = "drop" + (/*drag*/ ctx[1] ? " active" : "") + " svelte-1t99wk2")) {
				attr(div2, "class", div2_class_value);
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div2);
			if (detaching) detach(t2);
			if (detaching) detach(div3);
			if (detaching) detach(t4);
			if (detaching) detach(div4);
			mounted = false;
			run_all(dispose);
		}
	};
}

// (52:4) {#if mediaList.length > 0}
function create_if_block(ctx) {
	let mediagrid;
	let updating_selectedMedia;
	let t;
	let buttons;
	let current;

	function mediagrid_selectedMedia_binding(value) {
		/*mediagrid_selectedMedia_binding*/ ctx[9](value);
	}

	let mediagrid_props = {
		files: /*getThumbnails*/ ctx[7](/*mediaList*/ ctx[0])
	};

	if (/*selectedMedia*/ ctx[2] !== void 0) {
		mediagrid_props.selectedMedia = /*selectedMedia*/ ctx[2];
	}

	mediagrid = new MediaGrid({ props: mediagrid_props });
	binding_callbacks.push(() => bind(mediagrid, "selectedMedia", mediagrid_selectedMedia_binding));

	buttons = new Buttons({
			props: {
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			}
		});

	return {
		c() {
			create_component(mediagrid.$$.fragment);
			t = space();
			create_component(buttons.$$.fragment);
		},
		l(nodes) {
			claim_component(mediagrid.$$.fragment, nodes);
			t = claim_space(nodes);
			claim_component(buttons.$$.fragment, nodes);
		},
		m(target, anchor) {
			mount_component(mediagrid, target, anchor);
			insert(target, t, anchor);
			mount_component(buttons, target, anchor);
			current = true;
		},
		p(ctx, dirty) {
			const mediagrid_changes = {};
			if (dirty & /*mediaList*/ 1) mediagrid_changes.files = /*getThumbnails*/ ctx[7](/*mediaList*/ ctx[0]);

			if (!updating_selectedMedia && dirty & /*selectedMedia*/ 4) {
				updating_selectedMedia = true;
				mediagrid_changes.selectedMedia = /*selectedMedia*/ ctx[2];
				add_flush_callback(() => updating_selectedMedia = false);
			}

			mediagrid.$set(mediagrid_changes);
			const buttons_changes = {};

			if (dirty & /*$$scope, selectedMedia, mediaList*/ 32773) {
				buttons_changes.$$scope = { dirty, ctx };
			}

			buttons.$set(buttons_changes);
		},
		i(local) {
			if (current) return;
			transition_in(mediagrid.$$.fragment, local);
			transition_in(buttons.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(mediagrid.$$.fragment, local);
			transition_out(buttons.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(mediagrid, detaching);
			if (detaching) detach(t);
			destroy_component(buttons, detaching);
		}
	};
}

// (58:12) {:else}
function create_else_block(ctx) {
	let button;
	let t;
	let mounted;
	let dispose;

	return {
		c() {
			button = element("button");
			t = text("Discard all");
		},
		l(nodes) {
			button = claim_element(nodes, "BUTTON", {});
			var button_nodes = children(button);
			t = claim_text(button_nodes, "Discard all");
			button_nodes.forEach(detach);
		},
		m(target, anchor) {
			insert(target, button, anchor);
			append(button, t);

			if (!mounted) {
				dispose = listen(button, "click", prevent_default(/*click_handler*/ ctx[11]));
				mounted = true;
			}
		},
		p: noop,
		d(detaching) {
			if (detaching) detach(button);
			mounted = false;
			dispose();
		}
	};
}

// (56:12) {#if selectedMedia.length > 0}
function create_if_block_1(ctx) {
	let button;
	let t;
	let mounted;
	let dispose;

	return {
		c() {
			button = element("button");
			t = text("Discard selected");
		},
		l(nodes) {
			button = claim_element(nodes, "BUTTON", {});
			var button_nodes = children(button);
			t = claim_text(button_nodes, "Discard selected");
			button_nodes.forEach(detach);
		},
		m(target, anchor) {
			insert(target, button, anchor);
			append(button, t);

			if (!mounted) {
				dispose = listen(button, "click", prevent_default(/*removeSelectedMedia*/ ctx[6]));
				mounted = true;
			}
		},
		p: noop,
		d(detaching) {
			if (detaching) detach(button);
			mounted = false;
			dispose();
		}
	};
}

// (54:8) <Buttons>
function create_default_slot(ctx) {
	let save;
	let updating_mediaList;
	let t;
	let if_block_anchor;
	let current;

	function save_mediaList_binding(value) {
		/*save_mediaList_binding*/ ctx[10](value);
	}

	let save_props = { action: "create", encoding: "base64" };

	if (/*mediaList*/ ctx[0] !== void 0) {
		save_props.mediaList = /*mediaList*/ ctx[0];
	}

	save = new Save({ props: save_props });
	binding_callbacks.push(() => bind(save, "mediaList", save_mediaList_binding));

	function select_block_type_1(ctx, dirty) {
		if (/*selectedMedia*/ ctx[2].length > 0) return create_if_block_1;
		return create_else_block;
	}

	let current_block_type = select_block_type_1(ctx, -1);
	let if_block = current_block_type(ctx);

	return {
		c() {
			create_component(save.$$.fragment);
			t = space();
			if_block.c();
			if_block_anchor = empty();
		},
		l(nodes) {
			claim_component(save.$$.fragment, nodes);
			t = claim_space(nodes);
			if_block.l(nodes);
			if_block_anchor = empty();
		},
		m(target, anchor) {
			mount_component(save, target, anchor);
			insert(target, t, anchor);
			if_block.m(target, anchor);
			insert(target, if_block_anchor, anchor);
			current = true;
		},
		p(ctx, dirty) {
			const save_changes = {};

			if (!updating_mediaList && dirty & /*mediaList*/ 1) {
				updating_mediaList = true;
				save_changes.mediaList = /*mediaList*/ ctx[0];
				add_flush_callback(() => updating_mediaList = false);
			}

			save.$set(save_changes);

			if (current_block_type === (current_block_type = select_block_type_1(ctx, dirty)) && if_block) {
				if_block.p(ctx, dirty);
			} else {
				if_block.d(1);
				if_block = current_block_type(ctx);

				if (if_block) {
					if_block.c();
					if_block.m(if_block_anchor.parentNode, if_block_anchor);
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(save.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(save.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(save, detaching);
			if (detaching) detach(t);
			if_block.d(detaching);
			if (detaching) detach(if_block_anchor);
		}
	};
}

function create_fragment(ctx) {
	let div;
	let current_block_type_index;
	let if_block;
	let current;
	const if_block_creators = [create_if_block, create_else_block_1];
	const if_blocks = [];

	function select_block_type(ctx, dirty) {
		if (/*mediaList*/ ctx[0].length > 0) return 0;
		return 1;
	}

	current_block_type_index = select_block_type(ctx, -1);
	if_block = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);

	return {
		c() {
			div = element("div");
			if_block.c();
			this.h();
		},
		l(nodes) {
			div = claim_element(nodes, "DIV", { class: true });
			var div_nodes = children(div);
			if_block.l(div_nodes);
			div_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(div, "class", "upload-wrapper svelte-1t99wk2");
		},
		m(target, anchor) {
			insert(target, div, anchor);
			if_blocks[current_block_type_index].m(div, null);
			current = true;
		},
		p(ctx, [dirty]) {
			let previous_block_index = current_block_type_index;
			current_block_type_index = select_block_type(ctx, dirty);

			if (current_block_type_index === previous_block_index) {
				if_blocks[current_block_type_index].p(ctx, dirty);
			} else {
				group_outros();

				transition_out(if_blocks[previous_block_index], 1, 1, () => {
					if_blocks[previous_block_index] = null;
				});

				check_outros();
				if_block = if_blocks[current_block_type_index];

				if (!if_block) {
					if_block = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);
					if_block.c();
				} else {
					if_block.p(ctx, dirty);
				}

				transition_in(if_block, 1);
				if_block.m(div, null);
			}
		},
		i(local) {
			if (current) return;
			transition_in(if_block);
			current = true;
		},
		o(local) {
			transition_out(if_block);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(div);
			if_blocks[current_block_type_index].d();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let mediaList = [];

	const createMediaList = file => {
		let reader = new FileReader();
		reader.readAsDataURL(file);

		reader.onload = e => {
			$$invalidate(0, mediaList = [
				...mediaList,
				{
					file: "assets/" + file.name,
					contents: e.target.result
				}
			]);
		};
	};

	const selectFile = files => {
		Array.from(files).forEach(file => {
			createMediaList(file);
		});
	};

	let drag;

	const toggleDrag = () => {
		$$invalidate(1, drag = !drag);
	};

	const dropFile = ev => {
		if (ev.dataTransfer.items) {
			// Use DataTransferItemList interface to access the file(s)
			for (let i = 0; i < ev.dataTransfer.items.length; i++) {
				// If dropped items aren't files, reject them
				if (ev.dataTransfer.items[i].kind === "file") {
					let file = ev.dataTransfer.items[i].getAsFile();
					createMediaList(file);
				}
			}
		}
	};

	let selectedMedia = [];

	const removeSelectedMedia = () => {
		selectedMedia.forEach(file => {
			$$invalidate(0, mediaList = mediaList.filter(i => i.contents !== file));
			$$invalidate(2, selectedMedia = []);
		});
	};

	const getThumbnails = mediaList => mediaList.map(i => i.contents);

	function dragover_handler(event) {
		bubble.call(this, $$self, event);
	}

	function mediagrid_selectedMedia_binding(value) {
		selectedMedia = value;
		$$invalidate(2, selectedMedia);
	}

	function save_mediaList_binding(value) {
		mediaList = value;
		$$invalidate(0, mediaList);
	}

	const click_handler = () => $$invalidate(0, mediaList = []);
	const drop_handler = event => dropFile(event);
	const change_handler = event => selectFile(event.target.files);

	return [
		mediaList,
		drag,
		selectedMedia,
		selectFile,
		toggleDrag,
		dropFile,
		removeSelectedMedia,
		getThumbnails,
		dragover_handler,
		mediagrid_selectedMedia_binding,
		save_mediaList_binding,
		click_handler,
		drop_handler,
		change_handler
	];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Component;