/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_space,
	claim_text,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space,
	text
} from "svelte/internal";

import { makeTitle } from "../scripts/make_title.svelte";

function create_fragment(ctx) {
	let footer;
	let div9;
	let section0;
	let strong0;
	let t0;
	let t1;
	let div0;
	let a0;
	let t2;
	let t3;
	let div1;
	let a1;
	let t4;
	let t5;
	let section1;
	let strong1;
	let t6;
	let t7;
	let div2;
	let a2;
	let t8;
	let t9;
	let div3;
	let a3;
	let t10;
	let t11;
	let section2;
	let strong2;
	let t12;
	let t13;
	let div4;
	let a4;
	let t14;
	let t15;
	let div5;
	let a5;
	let t16;
	let t17;
	let div6;
	let a6;
	let t18;
	let t19;
	let section3;
	let div7;
	let a7;
	let img0;
	let img0_src_value;
	let a8;
	let img1;
	let img1_src_value;
	let a9;
	let img2;
	let img2_src_value;
	let t20;
	let div8;
	let t21;
	let t22;
	let a10;
	let t23;

	return {
		c() {
			footer = element("footer");
			div9 = element("div");
			section0 = element("section");
			strong0 = element("strong");
			t0 = text("Plentico");
			t1 = space();
			div0 = element("div");
			a0 = element("a");
			t2 = text("About");
			t3 = space();
			div1 = element("div");
			a1 = element("a");
			t4 = text("Contact");
			t5 = space();
			section1 = element("section");
			strong1 = element("strong");
			t6 = text("Products");
			t7 = space();
			div2 = element("div");
			a2 = element("a");
			t8 = text("Plenti");
			t9 = space();
			div3 = element("div");
			a3 = element("a");
			t10 = text("Plentiform");
			t11 = space();
			section2 = element("section");
			strong2 = element("strong");
			t12 = text("Resources");
			t13 = space();
			div4 = element("div");
			a4 = element("a");
			t14 = text("Documentation");
			t15 = space();
			div5 = element("div");
			a5 = element("a");
			t16 = text("Themes");
			t17 = space();
			div6 = element("div");
			a6 = element("a");
			t18 = text("Download");
			t19 = space();
			section3 = element("section");
			div7 = element("div");
			a7 = element("a");
			img0 = element("img");
			a8 = element("a");
			img1 = element("img");
			a9 = element("a");
			img2 = element("img");
			t20 = space();
			div8 = element("div");
			t21 = text("© Plentico 2021");
			t22 = space();
			a10 = element("a");
			t23 = text("By Jantcu LLC");
			this.h();
		},
		l(nodes) {
			footer = claim_element(nodes, "FOOTER", { class: true });
			var footer_nodes = children(footer);
			div9 = claim_element(footer_nodes, "DIV", { class: true });
			var div9_nodes = children(div9);
			section0 = claim_element(div9_nodes, "SECTION", { id: true, class: true });
			var section0_nodes = children(section0);
			strong0 = claim_element(section0_nodes, "STRONG", { class: true });
			var strong0_nodes = children(strong0);
			t0 = claim_text(strong0_nodes, "Plentico");
			strong0_nodes.forEach(detach);
			t1 = claim_space(section0_nodes);
			div0 = claim_element(section0_nodes, "DIV", {});
			var div0_nodes = children(div0);
			a0 = claim_element(div0_nodes, "A", { href: true, class: true });
			var a0_nodes = children(a0);
			t2 = claim_text(a0_nodes, "About");
			a0_nodes.forEach(detach);
			div0_nodes.forEach(detach);
			t3 = claim_space(section0_nodes);
			div1 = claim_element(section0_nodes, "DIV", {});
			var div1_nodes = children(div1);
			a1 = claim_element(div1_nodes, "A", { href: true, class: true });
			var a1_nodes = children(a1);
			t4 = claim_text(a1_nodes, "Contact");
			a1_nodes.forEach(detach);
			div1_nodes.forEach(detach);
			section0_nodes.forEach(detach);
			t5 = claim_space(div9_nodes);
			section1 = claim_element(div9_nodes, "SECTION", { id: true, class: true });
			var section1_nodes = children(section1);
			strong1 = claim_element(section1_nodes, "STRONG", { class: true });
			var strong1_nodes = children(strong1);
			t6 = claim_text(strong1_nodes, "Products");
			strong1_nodes.forEach(detach);
			t7 = claim_space(section1_nodes);
			div2 = claim_element(section1_nodes, "DIV", {});
			var div2_nodes = children(div2);
			a2 = claim_element(div2_nodes, "A", { href: true, class: true });
			var a2_nodes = children(a2);
			t8 = claim_text(a2_nodes, "Plenti");
			a2_nodes.forEach(detach);
			div2_nodes.forEach(detach);
			t9 = claim_space(section1_nodes);
			div3 = claim_element(section1_nodes, "DIV", {});
			var div3_nodes = children(div3);
			a3 = claim_element(div3_nodes, "A", { href: true, class: true });
			var a3_nodes = children(a3);
			t10 = claim_text(a3_nodes, "Plentiform");
			a3_nodes.forEach(detach);
			div3_nodes.forEach(detach);
			section1_nodes.forEach(detach);
			t11 = claim_space(div9_nodes);
			section2 = claim_element(div9_nodes, "SECTION", { id: true, class: true });
			var section2_nodes = children(section2);
			strong2 = claim_element(section2_nodes, "STRONG", { class: true });
			var strong2_nodes = children(strong2);
			t12 = claim_text(strong2_nodes, "Resources");
			strong2_nodes.forEach(detach);
			t13 = claim_space(section2_nodes);
			div4 = claim_element(section2_nodes, "DIV", {});
			var div4_nodes = children(div4);
			a4 = claim_element(div4_nodes, "A", { href: true, class: true });
			var a4_nodes = children(a4);
			t14 = claim_text(a4_nodes, "Documentation");
			a4_nodes.forEach(detach);
			div4_nodes.forEach(detach);
			t15 = claim_space(section2_nodes);
			div5 = claim_element(section2_nodes, "DIV", {});
			var div5_nodes = children(div5);
			a5 = claim_element(div5_nodes, "A", { href: true, class: true });
			var a5_nodes = children(a5);
			t16 = claim_text(a5_nodes, "Themes");
			a5_nodes.forEach(detach);
			div5_nodes.forEach(detach);
			t17 = claim_space(section2_nodes);
			div6 = claim_element(section2_nodes, "DIV", {});
			var div6_nodes = children(div6);
			a6 = claim_element(div6_nodes, "A", { href: true, class: true });
			var a6_nodes = children(a6);
			t18 = claim_text(a6_nodes, "Download");
			a6_nodes.forEach(detach);
			div6_nodes.forEach(detach);
			section2_nodes.forEach(detach);
			t19 = claim_space(div9_nodes);
			section3 = claim_element(div9_nodes, "SECTION", { id: true, class: true });
			var section3_nodes = children(section3);
			div7 = claim_element(section3_nodes, "DIV", { id: true, class: true });
			var div7_nodes = children(div7);
			a7 = claim_element(div7_nodes, "A", { href: true, class: true });
			var a7_nodes = children(a7);
			img0 = claim_element(a7_nodes, "IMG", { src: true });
			a7_nodes.forEach(detach);
			a8 = claim_element(div7_nodes, "A", { href: true, class: true });
			var a8_nodes = children(a8);
			img1 = claim_element(a8_nodes, "IMG", { src: true });
			a8_nodes.forEach(detach);
			a9 = claim_element(div7_nodes, "A", { href: true, class: true });
			var a9_nodes = children(a9);
			img2 = claim_element(a9_nodes, "IMG", { src: true });
			a9_nodes.forEach(detach);
			div7_nodes.forEach(detach);
			t20 = claim_space(section3_nodes);
			div8 = claim_element(section3_nodes, "DIV", { id: true });
			var div8_nodes = children(div8);
			t21 = claim_text(div8_nodes, "© Plentico 2021");
			div8_nodes.forEach(detach);
			t22 = claim_space(section3_nodes);
			a10 = claim_element(section3_nodes, "A", { href: true, class: true });
			var a10_nodes = children(a10);
			t23 = claim_text(a10_nodes, "By Jantcu LLC");
			a10_nodes.forEach(detach);
			section3_nodes.forEach(detach);
			div9_nodes.forEach(detach);
			footer_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(strong0, "class", "svelte-1v9u363");
			attr(a0, "href", "/about");
			attr(a0, "class", "svelte-1v9u363");
			attr(a1, "href", "/contact");
			attr(a1, "class", "svelte-1v9u363");
			attr(section0, "id", "plentico");
			attr(section0, "class", "svelte-1v9u363");
			attr(strong1, "class", "svelte-1v9u363");
			attr(a2, "href", "https://github.com/plentico/plenti");
			attr(a2, "class", "svelte-1v9u363");
			attr(a3, "href", "https://plentiform.com");
			attr(a3, "class", "svelte-1v9u363");
			attr(section1, "id", "products");
			attr(section1, "class", "svelte-1v9u363");
			attr(strong2, "class", "svelte-1v9u363");
			attr(a4, "href", "/docs");
			attr(a4, "class", "svelte-1v9u363");
			attr(a5, "href", "/themes");
			attr(a5, "class", "svelte-1v9u363");
			attr(a6, "href", "/download");
			attr(a6, "class", "svelte-1v9u363");
			attr(section2, "id", "resources");
			attr(section2, "class", "svelte-1v9u363");
			if (img0.src !== (img0_src_value = "/assets/social/twitter.svg")) attr(img0, "src", img0_src_value);
			attr(a7, "href", "https://twitter.com/plentico");
			attr(a7, "class", "svelte-1v9u363");
			if (img1.src !== (img1_src_value = "/assets/social/youtube.svg")) attr(img1, "src", img1_src_value);
			attr(a8, "href", "https://youtube.com/jantcu");
			attr(a8, "class", "svelte-1v9u363");
			if (img2.src !== (img2_src_value = "/assets/social/github.svg")) attr(img2, "src", img2_src_value);
			attr(a9, "href", "https://github.com/plentico/plenti");
			attr(a9, "class", "svelte-1v9u363");
			attr(div7, "id", "social");
			attr(div7, "class", "svelte-1v9u363");
			attr(div8, "id", "copyright");
			attr(a10, "href", "https://jantcu.com");
			attr(a10, "class", "svelte-1v9u363");
			attr(section3, "id", "copyright");
			attr(section3, "class", "svelte-1v9u363");
			attr(div9, "class", "container svelte-1v9u363");
			attr(footer, "class", "svelte-1v9u363");
		},
		m(target, anchor) {
			insert(target, footer, anchor);
			append(footer, div9);
			append(div9, section0);
			append(section0, strong0);
			append(strong0, t0);
			append(section0, t1);
			append(section0, div0);
			append(div0, a0);
			append(a0, t2);
			append(section0, t3);
			append(section0, div1);
			append(div1, a1);
			append(a1, t4);
			append(div9, t5);
			append(div9, section1);
			append(section1, strong1);
			append(strong1, t6);
			append(section1, t7);
			append(section1, div2);
			append(div2, a2);
			append(a2, t8);
			append(section1, t9);
			append(section1, div3);
			append(div3, a3);
			append(a3, t10);
			append(div9, t11);
			append(div9, section2);
			append(section2, strong2);
			append(strong2, t12);
			append(section2, t13);
			append(section2, div4);
			append(div4, a4);
			append(a4, t14);
			append(section2, t15);
			append(section2, div5);
			append(div5, a5);
			append(a5, t16);
			append(section2, t17);
			append(section2, div6);
			append(div6, a6);
			append(a6, t18);
			append(div9, t19);
			append(div9, section3);
			append(section3, div7);
			append(div7, a7);
			append(a7, img0);
			append(div7, a8);
			append(a8, img1);
			append(div7, a9);
			append(a9, img2);
			append(section3, t20);
			append(section3, div8);
			append(div8, t21);
			append(section3, t22);
			append(section3, a10);
			append(a10, t23);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(footer);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;