/* generated by Svelte v3.23.0 */
import {
	SvelteComponent,
	append,
	assign,
	attr,
	check_outros,
	create_component,
	destroy_component,
	detach,
	element,
	get_spread_object,
	get_spread_update,
	group_outros,
	init,
	insert,
	mount_component,
	safe_not_equal,
	space,
	transition_in,
	transition_out
} from '/spa/web_modules/svelte/internal/index.js';

import Head from '/spa/global/./head.js';
import Nav from '/spa/global/./nav.js';
import Footer from '/spa/global/./footer.js';
import { makeTitle } from '/spa/global/../scripts/make_title.js';

function create_fragment(ctx) {
	let html;
	let t0;
	let body;
	let t1;
	let main;
	let t2;
	let br;
	let t3;
	let current;

	const head = new Head({
			props: {
				title: makeTitle(/*node*/ ctx[1].filename)
			}
		});

	const nav = new Nav({});
	const switch_instance_spread_levels = [/*node*/ ctx[1].fields, { allNodes: /*allNodes*/ ctx[2] }];
	var switch_value = /*route*/ ctx[0];

	function switch_props(ctx) {
		let switch_instance_props = {};

		for (let i = 0; i < switch_instance_spread_levels.length; i += 1) {
			switch_instance_props = assign(switch_instance_props, switch_instance_spread_levels[i]);
		}

		return { props: switch_instance_props };
	}

	if (switch_value) {
		var switch_instance = new switch_value(switch_props(ctx));
	}

	const footer = new Footer({});

	return {
		c() {
			html = element("html");
			create_component(head.$$.fragment);
			t0 = space();
			body = element("body");
			create_component(nav.$$.fragment);
			t1 = space();
			main = element("main");
			if (switch_instance) create_component(switch_instance.$$.fragment);
			t2 = space();
			br = element("br");
			t3 = space();
			create_component(footer.$$.fragment);
			attr(main, "class", "svelte-1142p5h");
			attr(body, "class", "svelte-1142p5h");
			attr(html, "lang", "en");
		},
		m(target, anchor) {
			insert(target, html, anchor);
			mount_component(head, html, null);
			append(html, t0);
			append(html, body);
			mount_component(nav, body, null);
			append(body, t1);
			append(body, main);

			if (switch_instance) {
				mount_component(switch_instance, main, null);
			}

			append(main, t2);
			append(main, br);
			append(body, t3);
			mount_component(footer, body, null);
			current = true;
		},
		p(ctx, [dirty]) {
			const head_changes = {};
			if (dirty & /*node*/ 2) head_changes.title = makeTitle(/*node*/ ctx[1].filename);
			head.$set(head_changes);

			const switch_instance_changes = (dirty & /*node, allNodes*/ 6)
			? get_spread_update(switch_instance_spread_levels, [
					dirty & /*node*/ 2 && get_spread_object(/*node*/ ctx[1].fields),
					dirty & /*allNodes*/ 4 && { allNodes: /*allNodes*/ ctx[2] }
				])
			: {};

			if (switch_value !== (switch_value = /*route*/ ctx[0])) {
				if (switch_instance) {
					group_outros();
					const old_component = switch_instance;

					transition_out(old_component.$$.fragment, 1, 0, () => {
						destroy_component(old_component, 1);
					});

					check_outros();
				}

				if (switch_value) {
					switch_instance = new switch_value(switch_props(ctx));
					create_component(switch_instance.$$.fragment);
					transition_in(switch_instance.$$.fragment, 1);
					mount_component(switch_instance, main, t2);
				} else {
					switch_instance = null;
				}
			} else if (switch_value) {
				switch_instance.$set(switch_instance_changes);
			}
		},
		i(local) {
			if (current) return;
			transition_in(head.$$.fragment, local);
			transition_in(nav.$$.fragment, local);
			if (switch_instance) transition_in(switch_instance.$$.fragment, local);
			transition_in(footer.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(head.$$.fragment, local);
			transition_out(nav.$$.fragment, local);
			if (switch_instance) transition_out(switch_instance.$$.fragment, local);
			transition_out(footer.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(html);
			destroy_component(head);
			destroy_component(nav);
			if (switch_instance) destroy_component(switch_instance);
			destroy_component(footer);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { route } = $$props, { node } = $$props, { allNodes } = $$props;

	$$self.$set = $$props => {
		if ("route" in $$props) $$invalidate(0, route = $$props.route);
		if ("node" in $$props) $$invalidate(1, node = $$props.node);
		if ("allNodes" in $$props) $$invalidate(2, allNodes = $$props.allNodes);
	};

	return [route, node, allNodes];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { route: 0, node: 1, allNodes: 2 });
	}
}

export default Component;