/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	claim_component,
	create_component,
	destroy_component,
	init,
	mount_component,
	safe_not_equal,
	transition_in,
	transition_out
} from '../web_modules/svelte/internal/index.mjs';

import Navaid from '../web_modules/navaid/dist/navaid.mjs';
import Html from '../global/html.js';
import { getContent } from './main.js';

function create_fragment(ctx) {
	let html;
	let current;

	html = new Html({
			props: {
				content: /*content*/ ctx[0],
				layout: /*layout*/ ctx[1],
				allContent: /*allContent*/ ctx[2],
				allLayouts: /*allLayouts*/ ctx[3],
				env: /*env*/ ctx[4]
			}
		});

	return {
		c() {
			create_component(html.$$.fragment);
		},
		l(nodes) {
			claim_component(html.$$.fragment, nodes);
		},
		m(target, anchor) {
			mount_component(html, target, anchor);
			current = true;
		},
		p(ctx, [dirty]) {
			const html_changes = {};
			if (dirty & /*content*/ 1) html_changes.content = /*content*/ ctx[0];
			if (dirty & /*layout*/ 2) html_changes.layout = /*layout*/ ctx[1];
			if (dirty & /*allContent*/ 4) html_changes.allContent = /*allContent*/ ctx[2];
			if (dirty & /*allLayouts*/ 8) html_changes.allLayouts = /*allLayouts*/ ctx[3];
			if (dirty & /*env*/ 16) html_changes.env = /*env*/ ctx[4];
			html.$set(html_changes);
		},
		i(local) {
			if (current) return;
			transition_in(html.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(html.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(html, detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { uri } = $$props,
		{ content } = $$props,
		{ layout } = $$props,
		{ allContent } = $$props,
		{ allLayouts } = $$props,
		{ env } = $$props;

	function draw(m) {
		$$invalidate(0, content = getContent(uri));

		if (content === undefined) {
			// Check if there is a 404 data source.
			$$invalidate(0, content = getContent("/404"));

			if (content === undefined) {
				// If no 404.json data source exists, pass placeholder values.
				$$invalidate(0, content = {
					"path": "/404",
					"type": "404",
					"filename": "404.json",
					"fields": {}
				});
			}
		}

		$$invalidate(1, layout = m.default);
		window.scrollTo(0, 0);
	}

	function track(obj) {
		$$invalidate(5, uri = obj.state || obj.uri);
	}

	addEventListener("replacestate", track);
	addEventListener("pushstate", track);
	addEventListener("popstate", track);

	const handle404 = () => {
		import("../content/404.js").then(draw).catch(err => {
			console.log("Add a '/layouts/content/404.svelte' file to handle Page Not Found errors.");
			console.log("If you want to pass data to your 404 component, you can also add a '/content/404.json' file.");
			console.log(err);
		});
	};

	const router = Navaid("/", handle404);

	allContent.forEach(content => {
		router.on((env.local ? "" : env.baseurl) + content.path, () => {
			import("../content/" + content.type + ".js").then(draw).catch(handle404);
		});
	});

	router.listen();

	// Fix browser back button for initially loaded page.
	router.route(uri, false);

	$$self.$$set = $$props => {
		if ("uri" in $$props) $$invalidate(5, uri = $$props.uri);
		if ("content" in $$props) $$invalidate(0, content = $$props.content);
		if ("layout" in $$props) $$invalidate(1, layout = $$props.layout);
		if ("allContent" in $$props) $$invalidate(2, allContent = $$props.allContent);
		if ("allLayouts" in $$props) $$invalidate(3, allLayouts = $$props.allLayouts);
		if ("env" in $$props) $$invalidate(4, env = $$props.env);
	};

	return [content, layout, allContent, allLayouts, env, uri];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			uri: 5,
			content: 0,
			layout: 1,
			allContent: 2,
			allLayouts: 3,
			env: 4
		});
	}
}

export default Component;