/* generated by Svelte v3.32.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_text,
	detach,
	init,
	insert,
	noop,
	safe_not_equal,
	svg_element,
	text
} from '/spa/web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let svg;
	let metadata;
	let rdf_RDF;
	let cc_Work;
	let dc_format;
	let t;
	let dc_type;
	let dc_title;
	let g1;
	let g0;
	let path0;
	let path1;

	return {
		c() {
			svg = svg_element("svg");
			metadata = svg_element("metadata");
			rdf_RDF = svg_element("rdf:RDF");
			cc_Work = svg_element("cc:Work");
			dc_format = svg_element("dc:format");
			t = text("image/svg+xml");
			dc_type = svg_element("dc:type");
			dc_title = svg_element("dc:title");
			g1 = svg_element("g");
			g0 = svg_element("g");
			path0 = svg_element("path");
			path1 = svg_element("path");
			this.h();
		},
		l(nodes) {
			svg = claim_element(
				nodes,
				"svg",
				{
					"enable-background": true,
					version: true,
					viewBox: true,
					"xml:space": true,
					xmlns: true,
					"xmlns:cc": true,
					"xmlns:dc": true,
					"xmlns:rdf": true
				},
				1
			);

			var svg_nodes = children(svg);
			metadata = claim_element(svg_nodes, "metadata", {}, 1);
			var metadata_nodes = children(metadata);
			rdf_RDF = claim_element(metadata_nodes, "rdf:RDF", {}, 1);
			var rdf_RDF_nodes = children(rdf_RDF);
			cc_Work = claim_element(rdf_RDF_nodes, "cc:Work", { "rdf:about": true }, 1);
			var cc_Work_nodes = children(cc_Work);
			dc_format = claim_element(cc_Work_nodes, "dc:format", {}, 1);
			var dc_format_nodes = children(dc_format);
			t = claim_text(dc_format_nodes, "image/svg+xml");
			dc_format_nodes.forEach(detach);
			dc_type = claim_element(cc_Work_nodes, "dc:type", { "rdf:resource": true }, 1);
			children(dc_type).forEach(detach);
			dc_title = claim_element(cc_Work_nodes, "dc:title", {}, 1);
			children(dc_title).forEach(detach);
			cc_Work_nodes.forEach(detach);
			rdf_RDF_nodes.forEach(detach);
			metadata_nodes.forEach(detach);
			g1 = claim_element(svg_nodes, "g", { fill: true }, 1);
			var g1_nodes = children(g1);
			g0 = claim_element(g1_nodes, "g", { fill: true }, 1);
			var g0_nodes = children(g0);
			path0 = claim_element(g0_nodes, "path", { d: true }, 1);
			children(path0).forEach(detach);
			path1 = claim_element(g0_nodes, "path", { d: true }, 1);
			children(path1).forEach(detach);
			g0_nodes.forEach(detach);
			g1_nodes.forEach(detach);
			svg_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(dc_type, "rdf:resource", "http://purl.org/dc/dcmitype/StillImage");
			attr(cc_Work, "rdf:about", "");
			attr(path0, "d", "m10.668 7.333c-0.018-1.749 1.426-2.586 1.49-2.628-0.811-1.185-2.073-1.348-2.524-1.366-1.073-0.11-2.096 0.632-2.642 0.632-0.544 0-1.386-0.617-2.277-0.601-1.172 0.018-2.251 0.682-2.855 1.73-1.217 2.112-0.312 5.24 0.874 6.955 0.58 0.838 1.272 1.779 2.179 1.746 0.874-0.035 1.204-0.566 2.261-0.566s1.354 0.566 2.278 0.549c0.941-0.018 1.536-0.855 2.111-1.695 0.666-0.973 0.94-1.916 0.957-1.963-0.022-0.012-1.833-0.705-1.852-2.793z");
			attr(path1, "d", "M 8.93,2.204 C 9.411,1.621 9.737,0.809 9.648,0 8.953,0.028 8.114,0.461 7.615,1.045 7.168,1.562 6.779,2.387 6.883,3.18 7.657,3.241 8.449,2.786 8.93,2.204 Z");
			attr(g0, "fill", "#3c3c3c");
			attr(g1, "fill", "#3c3c3c");
			attr(svg, "enable-background", "new 0 0 13.802 13.802");
			attr(svg, "version", "1.1");
			attr(svg, "viewBox", "0 0 13.802 13.802");
			attr(svg, "xml:space", "preserve");
			attr(svg, "xmlns", "http://www.w3.org/2000/svg");
			attr(svg, "xmlns:cc", "http://creativecommons.org/ns#");
			attr(svg, "xmlns:dc", "http://purl.org/dc/elements/1.1/");
			attr(svg, "xmlns:rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#");
		},
		m(target, anchor) {
			insert(target, svg, anchor);
			append(svg, metadata);
			append(metadata, rdf_RDF);
			append(rdf_RDF, cc_Work);
			append(cc_Work, dc_format);
			append(dc_format, t);
			append(cc_Work, dc_type);
			append(cc_Work, dc_title);
			append(svg, g1);
			append(g1, g0);
			append(g0, path0);
			append(g0, path1);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(svg);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;