/* generated by Svelte v3.23.2 */
import {
	SvelteComponent,
	append,
	attr,
	detach,
	init,
	insert,
	noop,
	safe_not_equal,
	svg_element,
	text
} from '/spa/web_modules/svelte/internal/index.js';

function create_fragment(ctx) {
	let svg;
	let metadata;
	let rdf_RDF;
	let cc_Work;
	let dc_format;
	let t;
	let dc_type;
	let dc_title;
	let g4;
	let g0;
	let polygon0;
	let g1;
	let polygon1;
	let g2;
	let polygon2;
	let g3;
	let polygon3;

	return {
		c() {
			svg = svg_element("svg");
			metadata = svg_element("metadata");
			rdf_RDF = svg_element("rdf:RDF");
			cc_Work = svg_element("cc:Work");
			dc_format = svg_element("dc:format");
			t = text("image/svg+xml");
			dc_type = svg_element("dc:type");
			dc_title = svg_element("dc:title");
			g4 = svg_element("g");
			g0 = svg_element("g");
			polygon0 = svg_element("polygon");
			g1 = svg_element("g");
			polygon1 = svg_element("polygon");
			g2 = svg_element("g");
			polygon2 = svg_element("polygon");
			g3 = svg_element("g");
			polygon3 = svg_element("polygon");
			attr(dc_type, "rdf:resource", "http://purl.org/dc/dcmitype/StillImage");
			attr(cc_Work, "rdf:about", "");
			attr(polygon0, "points", "224 52 0 80 0 240 224 240");
			attr(polygon0, "fill", "#3c3c3c");
			attr(g0, "fill", "#3c3c3c");
			attr(polygon1, "points", "512 240 512 16 256 48 256 240");
			attr(polygon1, "fill", "#3c3c3c");
			attr(g1, "fill", "#3c3c3c");
			attr(polygon2, "points", "512 272 256 272 256 464 512 496");
			attr(polygon2, "fill", "#3c3c3c");
			attr(g2, "fill", "#3c3c3c");
			attr(polygon3, "points", "224 272 0 272 0 432 224 460");
			attr(polygon3, "fill", "#3c3c3c");
			attr(g3, "fill", "#3c3c3c");
			attr(g4, "fill", "#3c3c3c");
			attr(svg, "enable-background", "new 0 0 512 512");
			attr(svg, "version", "1.1");
			attr(svg, "viewBox", "0 0 512 512");
			attr(svg, "xml:space", "preserve");
			attr(svg, "xmlns", "http://www.w3.org/2000/svg");
			attr(svg, "xmlns:cc", "http://creativecommons.org/ns#");
			attr(svg, "xmlns:dc", "http://purl.org/dc/elements/1.1/");
			attr(svg, "xmlns:rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#");
		},
		m(target, anchor) {
			insert(target, svg, anchor);
			append(svg, metadata);
			append(metadata, rdf_RDF);
			append(rdf_RDF, cc_Work);
			append(cc_Work, dc_format);
			append(dc_format, t);
			append(cc_Work, dc_type);
			append(cc_Work, dc_title);
			append(svg, g4);
			append(g4, g0);
			append(g0, polygon0);
			append(g4, g1);
			append(g1, polygon1);
			append(g4, g2);
			append(g2, polygon2);
			append(g4, g3);
			append(g3, polygon3);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(svg);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;